version: '3.8'

services:
    app:
        build: .
        container_name: titanhub_app
        ports:
            - "8040:80"
        volumes:
            - ./:/var/www/html
        networks:
            - titanhub
        depends_on:
            - mysql
            - redis

    mysql:
        image: mysql:8.0
        container_name: titanhub_mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: titanhub
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3340:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - titanhub

    redis:
        image: redis:7
        container_name: titanhub_redis
        ports:
            - "6340:6379"
        networks:
            - titanhub

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: titanhub_phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_USER: user
            PMA_PASSWORD: password
        ports:
            - "8040:80"
        depends_on:
            - mysql
        networks:
            - titanhub

networks:
    titanhub:

volumes:
    dbdata:
